{{- $root := . -}}
{{- range $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "jina-serving.fullname" $root) $service.role | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "jina-serving.commonLabels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $service.role }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/component: {{ $service.role }}
  ports:
    - name: http
      port: {{ $service.servicePort }}
      targetPort: http
      protocol: TCP
{{- end }}
